<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="DiceRoller.BuildingBlocks.Contracts" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiceRoller.UserAccess.Domain\DiceRoller.UserAccess.Domain.csproj" />
  </ItemGroup>

</Project>
