<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="DiceRoller.BuildingBlocks.Web" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DiceRoller.UserAccess.Application\DiceRoller.UserAccess.Application.csproj" />
    <ProjectReference Include="..\DiceRoller.UserAccess.Infrastructure\DiceRoller.UserAccess.Infrastructure.csproj" />
  </ItemGroup>

</Project>
